services:
  proposta-api:
    build:
      context: .
      dockerfile: src/PropostaService.API/Dockerfile
    container_name: proposta-api
    restart: on-failure
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=proposta_db;Username=admin;Password=admin;
      - RabbitMq__Host=rabbitmq
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:8080"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - shared-net
    volumes:
      - ./proposta-logs:/app/Logs

volumes:
  postgres_data:
    name: seguradora-postgres-data

networks:
  shared-net:
    name: seguradora-network
    driver: bridge